Hooks:PreHook(NetworkPeer,"destroy","qc_on_peer_removed",function(self)
	local peer_id = self:id()
--	QuickChat:Log("QuickChat: Disconnected peer_id " .. tostring(peer_id))
	QuickChat:OnPeerDisconnected(peer_id)
end)